# -*- coding: utf-8 -*-
"""Ad-Hoc Analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13WMRzFC1m9KGAWE26ZAi683PDMf1DpY3
"""

# This script requires the data generated from ecommerce_data_gen.py
# It executes the ad-hoc investigation regarding profitability and bot behavior.

import pyspark.sql.functions as F
from pyspark.sql.window import Window

# Load the Delta table
DATA_PATH = "/tmp/ecommerce_transactions_delta"
df = spark.read.format("delta").load(DATA_PATH)

print("--- PART 1: COHORT PROFITABILITY ANALYSIS ---")
# Hypothesis: Users whose first purchase is a flash sale have a deeply negative lifetime value (LTV).
# We must look at margin, not just revenue.

# 1. Identify the first transaction for every user
user_window = Window.partitionBy("user_id").orderBy("transaction_timestamp")

df_with_rank = df.withColumn("txn_rank", F.row_number().over(user_window))

# 2. Tag users based on their acquisition channel (Flash Sale vs Organic)
acquisition_cohorts = df_with_rank.filter(F.col("txn_rank") == 1) \
    .select("user_id", F.col("is_flash_sale").alias("acquired_via_flash_sale"))

# 3. Calculate Lifetime Margin per User
user_ltv = df.groupBy("user_id").agg(
    F.sum("margin_usd").alias("lifetime_margin"),
    F.count("transaction_id").alias("total_purchases")
)

# 4. Join and Aggregate by Cohort and Product Category
cohort_analysis = user_ltv.join(acquisition_cohorts, "user_id") \
    .join(df.select("user_id", "product_category").distinct(), "user_id") \
    .groupBy("acquired_via_flash_sale", "product_category") \
    .agg(
        F.count("user_id").alias("user_count"),
        F.avg("total_purchases").alias("avg_purchases_per_user"),
        F.avg("lifetime_margin").alias("avg_lifetime_margin_usd"),
        F.sum("lifetime_margin").alias("total_cohort_margin")
    ).orderBy("acquired_via_flash_sale", "product_category")

cohort_analysis.display()


print("--- PART 2: BOT EXPLOITATION DETECTION ---")
# Hypothesis: High transaction velocity from single IPs during flash sales indicates inventory hoarding scripts.

# 1. Filter for Flash Sales only
flash_sales_df = df.filter(F.col("is_flash_sale") == True)

# 2. Define a time window to detect velocity.
# We look for IPs making more than 5 purchases within a 60-second rolling window.
# We cast timestamp to long (Unix epoch) for numeric windowing.
velocity_window = Window.partitionBy("ip_address").orderBy(F.col("transaction_timestamp").cast("long")) \
    .rangeBetween(-60, 0) # 60 seconds looking back

# 3. Count transactions within that window
bot_detection = flash_sales_df.withColumn("txns_in_last_60s", F.count("transaction_id").over(velocity_window))

# 4. Filter for anomalous behavior and correlate with VoltEdge specific indicators
anomalous_ips = bot_detection.filter(F.col("txns_in_last_60s") > 5) \
    .groupBy("ip_address") \
    .agg(
        F.max("txns_in_last_60s").alias("peak_txns_per_minute"),
        F.countDistinct("user_id").alias("unique_accounts_used"),
        F.avg("account_age_days").alias("avg_account_age_days"),
        F.collect_set("payment_method").alias("payment_methods_used"),
        F.collect_set("shipping_speed").alias("shipping_speeds_used"),
        F.sum("margin_usd").alias("margin_impact")
    ).orderBy(F.col("peak_txns_per_minute").desc())

anomalous_ips.display()

# Logical Critique for the Analyst:
# If 'unique_accounts_used' > 1 for these IPs, the bots are circumventing standard "1 per customer" limits
# by using multiple burner accounts routed through the same IP. Banning the user_id is ineffective;
# the business must implement velocity rate-limiting at the network/WAF layer based on this IP data.