# -*- coding: utf-8 -*-
"""Data Generation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vuIwABzTSVdK6dkMp8tLNGFoT_rE2CkZ
"""

# This script is designed to run in a Databricks notebook.
# It leverages Spark's distributed architecture to generate 6.5 million rows in seconds,
# exposing the inefficiency of using single-node Python for big data synthesis.

import pyspark.sql.functions as F
from pyspark.sql.types import IntegerType, StringType, DoubleType, TimestampType

# Configuration
NUM_RECORDS = 6500000
OUTPUT_PATH = "/tmp/ecommerce_transactions_delta"

def generate_ecommerce_data(spark):
    """
    Generates synthetic e-commerce transaction data using distributed Spark operations.
    Avoids UDFs (User Defined Functions) to prevent serialization overhead.
    """

    # Create a base dataframe of 6.5 million rows
    df = spark.range(NUM_RECORDS)

    # 1. Transaction IDs and Timestamps (Spread over the last 90 days)
    df = df.withColumn("transaction_id", F.expr("uuid()"))
    df = df.withColumn("seconds_offset", F.round(F.rand() * (90 * 24 * 60 * 60)))
    df = df.withColumn("transaction_timestamp", F.expr("current_timestamp() - interval 1 second * seconds_offset"))

    # 2. User & Product simulation
    # 1.5M unique users, 50k unique products
    df = df.withColumn("user_id", (F.rand() * 1500000).cast(IntegerType()))
    df = df.withColumn("product_id", (F.rand() * 50000).cast(IntegerType()))

    # 3. Financials
    # Base price between $10 and $1010
    df = df.withColumn("base_price", F.round((F.rand() * 1000) + 10, 2))

    # Simulate Flash Sales (15% of transactions are part of a flash sale with heavy discounts)
    df = df.withColumn("is_flash_sale", F.when(F.rand() < 0.15, True).otherwise(False))

    # Discount logic: Flash sales get 40-80% off. Normal sales get 0-10% off.
    df = df.withColumn("discount_rate",
                       F.when(F.col("is_flash_sale"), F.round((F.rand() * 0.4) + 0.4, 2))
                        .otherwise(F.round(F.rand() * 0.1, 2)))

    df = df.withColumn("final_price", F.round(F.col("base_price") * (1 - F.col("discount_rate")), 2))
    df = df.withColumn("margin_usd", F.round(F.col("final_price") - (F.col("base_price") * 0.6), 2)) # Assuming 40% standard markup

    # 4. Device and IP Simulation for anomaly detection
    # Introduce deliberate bot behavior: specific IPs generating rapid transactions
    # 5% of traffic comes from a small pool of 100 "suspicious" IPs. The rest from 2M random IPs.
    df = df.withColumn("is_suspicious_traffic", F.when(F.rand() < 0.05, True).otherwise(False))

    df = df.withColumn("ip_address",
                       F.when(F.col("is_suspicious_traffic"),
                              F.concat(F.lit("192.168.1."), (F.rand() * 100).cast(IntegerType()).cast(StringType())))
                        .otherwise(
                              F.concat((F.rand() * 255).cast(IntegerType()).cast(StringType()), F.lit("."),
                                       (F.rand() * 255).cast(IntegerType()).cast(StringType()), F.lit(".x.x"))))

    # Select and reorder columns
    final_df = df.select(
        "transaction_id", "transaction_timestamp", "user_id", "product_id",
        "base_price", "discount_rate", "final_price", "margin_usd",
        "is_flash_sale", "ip_address"
    )

    # Write out as a Delta table (Native to Databricks)
    final_df.write.format("delta").mode("overwrite").save(OUTPUT_PATH)
    print(f"Successfully generated {NUM_RECORDS} rows to {OUTPUT_PATH}")

    return final_df

# spark is implicitly available in Databricks notebooks
# df = generate_ecommerce_data(spark)